/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.12/samples
 */

plugins {
	java
}

tasks.named<Jar>("jar") {
	manifest {
		attributes["Main-Class"] = "com.Publisher"
	}
}

repositories {
	mavenCentral()
}

dependencies {
				// https://mvnrepository.com/artifact/com.sun.xml.ws/jaxws-rt
				implementation("com.sun.xml.ws:jaxws-rt:4.0.3")
				// https://mvnrepository.com/artifact/jakarta.jws/jakarta.jws-api
				implementation("jakarta.jws:jakarta.jws-api:3.0.0")
				// https://mvnrepository.com/artifact/jakarta.xml.ws/jakarta.xml.ws-api
				implementation("jakarta.xml.ws:jakarta.xml.ws-api:4.0.2")
}
